server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: docker
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
    relabel_configs:
      - source_labels: [__meta_docker_container_name]
        regex: '/(.*)'
        target_label: container

  - job_name: auth_service
    static_configs:
      - targets:
          - localhost
        labels:
          job: auth_service
          __path__: /var/log/auth_service/*.log
          container: auth_service
    pipeline_stages:
      - json:
          expressions:
            time: time
            level: level
            service: service
            message: message
      - timestamp:
          source: time
          format: "2006-01-02 15:04:05.000000"
      - labels:
          level:
          service:

  - job_name: users_service
    static_configs:
      - targets:
          - localhost
        labels:
          job: users_service
          __path__: /var/log/users_service/*.log
          container: users_service
    pipeline_stages:
      - json:
          expressions:
            time: time
            level: level
            service: service
            message: message
      - timestamp:
          source: time
          format: "2006-01-02 15:04:05.000000"
      - labels:
          level:
          service:

  - job_name: minio_service
    static_configs:
      - targets:
          - localhost
        labels:
          job: minio_service
          __path__: /var/log/minio_service/*.log
          container: minio_service
    pipeline_stages:
      - json:
          expressions:
            time: time
            level: level
            service: service
            message: message
      - timestamp:
          source: time
          format: "2006-01-02 15:04:05.000000"
      - labels:
          level:
          service: 