"""empty message

Revision ID: cfe12f821696
Revises: f660f828317b
Create Date: 2025-06-01 12:46:55.493035

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cfe12f821696'
down_revision = 'f660f828317b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('order_id', sa.Integer(), nullable=False))
    op.drop_constraint('items_cart_id_fkey', 'items', type_='foreignkey')
    op.create_foreign_key(None, 'items', 'orders', ['order_id'], ['id'], ondelete='CASCADE')
    op.drop_column('items', 'cart_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('cart_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'items', type_='foreignkey')
    op.create_foreign_key('items_cart_id_fkey', 'items', 'orders', ['cart_id'], ['id'], ondelete='CASCADE')
    op.drop_column('items', 'order_id')
    # ### end Alembic commands ###
