version: '3.9'

services:
  # Minio
  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - '${MINIO_CONSOLE}:9001'
      - '${MINIO_PORT}:9000'
    volumes:
      - minio_data:/data
      - ./minio_certs:/root/.minio/certs:ro
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    networks:
      - monitoring
    command: minio server /data --console-address :9001

  minio_service:
    container_name: minio_service
    build:
      context: ./minio_service
    ports:
      - "${MINIO_SERVICE_PORT}:8000"
    volumes:
      - minio_logs:/var/log/minio_service
    env_file:
      - .env
    depends_on:
      - minio
    networks:
      - monitoring

  # Users/Auth
  auth_service:
    container_name: auth_service
    build:
      context: ./auth_service
    ports:
      - "${AUTH_PORT}:8000"
    env_file:
      - .env
    depends_on:
      users_postgres:
        condition: service_healthy
    networks:
      - monitoring

  users_service:
    container_name: users_service
    build:
      context: ./users_service
    ports:
      - "${USERS_PORT}:8000"
    env_file:
      - .env
    depends_on:
      users_postgres:
        condition: service_healthy
    networks:
      - monitoring

  users_postgres:
    container_name: users_postgres
    image: postgres:16.4-alpine3.20
    volumes:
      - users_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d ${USERS_POSTGRES_DB} -U ${USERS_POSTGRES_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_USER=${USERS_POSTGRES_USER}
      - POSTGRES_PASSWORD=${USERS_POSTGRES_PASSWORD}
      - POSTGRES_DB=${USERS_POSTGRES_DB}
    networks:
      - monitoring

  # Products
  products_postgres:
    image: debezium/postgres:15
    container_name: products_postgres
    environment:
      - POSTGRES_USER=${PRODUCTS_POSTGRES_USER}
      - POSTGRES_PASSWORD=${PRODUCTS_POSTGRES_PASSWORD}
      - POSTGRES_DB=${PRODUCTS_POSTGRES_DB}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d ${PRODUCTS_POSTGRES_DB} -U ${PRODUCTS_POSTGRES_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    command:
      - "postgres"
      - "-c"
      - "wal_level=logical"
      - "-c"
      - "max_replication_slots=4"
      - "-c"
      - "max_wal_senders=4"
    volumes:
      - products_data:/var/lib/postgresql/data
    networks:
      - monitoring

  products_service:
    container_name: products_service
    build:
      context: ./products_service
    ports:
      - "${PRODUCTS_PORT}:8000"
    env_file:
      - .env
    depends_on:
      products_postgres:
        condition: service_healthy
    networks:
      - monitoring

  # Kafka
  zookeeper:
    image: zookeeper:3.8
    container_name: zookeeper
    volumes:
      - zookeeper-data:/data
      - zookeeper-datalog:/datalog
    networks:
      - monitoring

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    environment:
      KAFKA_BROKER_ID: 101
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_DELETE_TOPIC_ENABLE: "true"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_HEAP_OPTS: "-Xmx512M -Xms256M"
    volumes:
      - kafka-data:/var/lib/kafka/data
    networks:
      - monitoring
    depends_on:
      - zookeeper

  # Debezium and elastic
  connect:
    image: debezium/connect:2.6
    container_name: connect
    environment:
      CONNECT_REST_ADVERTISED_HOST_NAME: "connect"
      CONNECT_REST_PORT: 8083

      BOOTSTRAP_SERVERS: "kafka:9092" # Kafka
      GROUP_ID: 1
      CONFIG_STORAGE_TOPIC: connect_configs
      OFFSET_STORAGE_TOPIC: connect_offsets
      STATUS_STORAGE_TOPIC: connect_statuses

      # ВАЖНО! НЕ МЕНЯТЬ
      KEY_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      VALUE_CONVERTER_SCHEMAS_ENABLE: "false"

      # плагины Elasticsearch и PostgreSQL
      CONNECT_PLUGIN_PATH: "/kafka/connect,/kafka/connect/debezium-connector-postgres,/kafka/connect/plugins"
    volumes:
      - ./connector-plugins:/kafka/connect/plugins
      - ./connector-configs:/tmp/configs
    networks:
      - monitoring
    depends_on:
      - products_postgres
      - kafka

  elasticsearch:
    image: elasticsearch:7.17.10
    container_name: elasticsearch
    environment:
      discovery.type: single-node
      xpack.security.enabled: "false"
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    networks:
      - monitoring
  # Logging
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
    - "9090:9090"
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    networks:
      - monitoring

  loki:
    image: grafana/loki:latest
    container_name: loki
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./loki:/etc/loki
      - loki_data:/loki
      - loki_wal:/wal
    user: "root"
    networks:
      - monitoring

  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    volumes:
      - ./loki/promtail-config.yaml:/etc/promtail/config.yaml
      - /var/run/docker.sock:/var/run/docker.sock
      - minio_logs:/var/log/minio_service
    command: -config.file=/etc/promtail/config.yaml
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "${GRAFANA_PORT}:3000"
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    depends_on:
      - prometheus
      - loki
    networks:
      - monitoring

networks:
  monitoring:
    driver: bridge

volumes:
  prometheus_data:
  loki_data:
  loki_wal:
  grafana_data:
  minio_logs:
  minio_data:
  users_data:
  products_data:
  zookeeper-data:
  zookeeper-datalog:
  kafka-data:
  esdata:
