version: '3.9'

services:
  users:
    container_name: fastapi_users
    build:
      context: ./users_service
    ports:
      - "${BACKEND_PORT}:8000"
    env_file:
      - .env
    volumes:
      - ${CERTS_PATH}/fullchain.pem:/app/fullchain.pem:ro
      - ${CERTS_PATH}/privkey.pem:/app/privkey.pem:ro
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:16.4-alpine3.20
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - ./mapped:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d ${POSTGRES_DB} -U ${POSTGRES_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
