version: '3.8'

services:
  web:
    container_name: fastapi_users
    build:
      context: .
      args:
          REQUIREMENTS_FILE: reqs.txt
    command: uvicorn src.app.main:app --port 8000 --host 0.0.0.0
    volumes:
      - .:/app
    ports:
      - "${BACKEND_PORT}:8000"
    depends_on:
      postgres:
        condition: service_healthy
  postgres:
    image: postgres:15-alpine
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - ./mapped:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d ${POSTGRES_DB} -U ${POSTGRES_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
