global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'auth_service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['auth_service:8000']

  - job_name: 'users_service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['users_service:8000']

  - job_name: 'minio_service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['minio_service:8000']

  - job_name: 'products_service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['products_service:8000'] 