global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'auth_service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['auth_service:8000']

  - job_name: 'users_service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['users_service:8000'] 