entryPoints:
  web:
    address: ":80"
  
  websecure: 
    address: ":443"

log:
  level: DEBUG

api:
  dashboard: true
  insecure: false

providers:
  docker:
    exposedByDefault: false
    network: monitoring

certificatesResolvers:
  letsencrypt:
    acme:
      email: demo.13b.gl@gmail.com       
      storage: /letsencrypt/acme.json
      httpChallenge:
        entryPoint: web

# Чтобы Traefik сохранял заголовки от /verify
forwardedHeaders:
  insecure: true